{{- if .Values.coordinator.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.coordinator" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator-hpa
    cluster-group: {{ .Values.clusterGroup }}
spec:
  maxReplicas: {{ .Values.coordinator.autoscaling.maxReplicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.coordinator" . }}
  metrics:
  {{- if .Values.coordinator.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.coordinator.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- if .Values.coordinator.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.coordinator.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{ if .Values.coordinator.autoscaling.behavior -}}
  behavior:
    {{- toYaml .Values.coordinator.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
