{{- $workerJmx := merge .Values.jmx.worker (omit .Values.jmx "coordinator" "worker") -}}
{{- if or .Values.server.keda.enabled (gt (int .Values.server.workers) 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.workerService" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    cluster-group: {{ .Values.clusterGroup }}
    cluster-instance: {{ template "trino.clusterInstance" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if $workerJmx.exporter.enabled }}
    - port: {{$workerJmx.exporter.port }}
      targetPort: jmx-exporter
      protocol: TCP
      name: jmx-exporter
    {{- end }}
    {{- range $key, $value := .Values.worker.additionalExposedPorts }}
    - port: {{ $value.servicePort }}
      name: {{ $value.name }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
      {{- if $value.nodePort }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "trino.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    cluster-group: {{ .Values.clusterGroup }}
    cluster-instance: {{ template "trino.clusterInstance" . }}
{{- end }}
