apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trino-kopf.fullname" . }}
  labels:
    app.kubernetes.io/component: kopf-deployment
    {{- include "trino-kopf.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trino-kopf.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kopf-operator
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: kopf-operator
        {{- include "trino-kopf.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "trino-kopf.serviceAccountName" . }}
      {{- if .Values.initContainers }}
      initContainers:
      {{- tpl (toYaml .Values.initContainers) . | nindent 6 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12}}
          ports:
            {{- if index .Values "config" "serverConfig" "http-server.http.enabled" }}
            - name: http
              containerPort: {{ index .Values "config" "serverConfig" "http-server.http.port" }}
              protocol: TCP
            {{- end }}
            {{- if index .Values "config" "serverConfig" "http-server.https.enabled" }}
            - name: https
              containerPort: {{ index .Values "config" "serverConfig" "http-server.https.port" }}
              protocol: TCP
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
