apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slave-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "events","pods/status", "namespaces", "services", "services/status"]
    verbs: ["list", "watch", "patch", "create"]

  - apiGroups: ["apps", "apiextensions.k8s.io"]
    resources: ["deployments", "customresourcedefinitions", "deployments/status"]
    verbs: ["get", "create", "list", "watch", "patch"]

  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "create", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slave-operator-binding
roleRef:
  kind: ClusterRole
  name: slave-operator-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: slave-operator
    namespace: default
