apiVersion: v1
kind: Service
metadata:
  name: cluster-operator-service
  labels:
    app.kubernetes.io/component: cluster-operator-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cluster-operator